### ISSUE TITLE
Speed and loading from gallery

### ISSUE THREAD

**Issue by gabrielfougeron** [gabrielfougeron/choreo#34]
Problems:
- Switching between different solutions, especially in the gallery gives the impression of VERY different speeds.
- Overall shape of the solution is not given immediately. Especially when the player is in pause.

**Comment by ivanosevitch** [comment]
Super nice, thanks!

**Comment by gabrielfougeron** [comment]
Speed is now recomputed less often. This is a problem since on startup, the screen refresh rate is assumed to be 60hz. Hence the super high speeds on my 144hz display.
