### ISSUE TITLE
Viewport impacts all mobile devices

### ISSUE THREAD

**Issue by gabrielfougeron** [gabrielfougeron/choreo#35]
On Ivans' Ipad, wiewport makes it behave as a phone, regardless of it being in landscape or portrait. That sucks.

**Comment by ivanosevitch** [comment]
I don't see anything that changed layout-wise on iPad?

![image](https://user-images.githubusercontent.com/15523557/202775866-9ab57bc2-4f1a-42e0-b7ba-4905feb55aa0.png)
![image](https://user-images.githubusercontent.com/15523557/202775883-57b1cdee-13dd-4d6b-86d0-6aef88ad6531.png)

**Comment by ivanosevitch** [comment]
It's better by forcing _Mobile device view > landscape_
I can now see that there are things below the animation without having to scroll to discover they exist at all. Also I can now change the speed without having to scroll away from the animation.

However the bottom frames still don't appear on the right of the animation, though it seems there would be just enough room?

![image](https://user-images.githubusercontent.com/15523557/202783391-0eae9ccd-e40f-4b0e-a922-277941a5d32a.png)

(On iPad 9th generation).

**Comment by ivanosevitch** [comment]
Frames are side-by-side by zooming at 85% on disable or landscape setting 😀 
![image](https://user-images.githubusercontent.com/15523557/202787390-9e6fbcb0-0cd2-454e-ae43-4d77bec93905.png)

**Comment by gabrielfougeron** [comment]
@ivanosevitch showed me yesterdayt that this is still far from satisfactory.

**Comment by ivanosevitch** [comment]
It's a bit better now:
At 100% with landscape setting, I can see both panes side by side. I though need to zoom out after selecting Landscape, as shown in this video:

https://github.com/gabrielfougeron/choreo/assets/15523557/4f209beb-4518-40f6-b602-57422db9f0
