### ISSUE TITLE
Bookmarks to gallery examples?

### ISSUE THREAD

**Issue by hoodmane** [gabrielfougeron/choreo#98]
I LOVE the choreo GUI
https://gabrielfougeron.github.io//choreo/

Whenever I show anyone an example of what Pyodide is good for I show them this. My only problem is I wish I could bookmark my favorite gallery example. Would you be willing to add bookmarks to the different gallery examples?

**Comment by hoodmane** [comment]
Yeah exactly. So if 
https://gabrielfougeron.github.io//choreo/#figure-8-in-circle-3
or
https://gabrielfougeron.github.io//choreo/&gallery-example=figure-8-in-circle-3
could take me to that particular example. Ideally also the buttons in the gallery should add the anchor to the url so that I can navigate to the appropriate example and then copy the link.

**Comment by gabrielfougeron** [comment]
Possible new UI presentation of share button:
 - remove animation control from main window (always on display) ==> put them under Animation.
 - Pute main share button instead. On click, create drop down to access options.
